apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP # LoadBalancer
  selector:
    app: web # rails-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http